# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Agenthound < Formula
  desc "AgentHound — lean field collector for AI agent infrastructure"
  homepage "https://github.com/adithyan-ak/agenthound"
  version "0.8.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/adithyan-ak/AgentHound/releases/download/v0.8.0/agenthound_0.8.0_darwin_amd64.tar.gz"
      sha256 "63936d1faf2473106eb7e40b360b42cf62a94a589148f00379c8bffeba3b5b1b"

      define_method(:install) do
        bin.install "agenthound"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/adithyan-ak/AgentHound/releases/download/v0.8.0/agenthound_0.8.0_darwin_arm64.tar.gz"
      sha256 "f035dc513fce7f4afc14d2cb42738da29ad40ce141949a8f9d1b1cd769e03c01"

      define_method(:install) do
        bin.install "agenthound"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/adithyan-ak/AgentHound/releases/download/v0.8.0/agenthound_0.8.0_linux_amd64.tar.gz"
      sha256 "e91253aa257773d17eec6a50459483050cf63f70054888f6348a11e94653e377"
      define_method(:install) do
        bin.install "agenthound"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/adithyan-ak/AgentHound/releases/download/v0.8.0/agenthound_0.8.0_linux_arm64.tar.gz"
      sha256 "42788930d13b828c7044c61d3a5decf68d512103a59d843ae715d954aa16984e"
      define_method(:install) do
        bin.install "agenthound"
      end
    end
  end

  test do
    assert_match "agenthound", shell_output("#{bin}/agenthound --version")
  end
end
