# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Agenthound < Formula
  desc "AgentHound — lean field collector for AI agent infrastructure"
  homepage "https://github.com/adithyan-ak/agenthound"
  version "0.6.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/adithyan-ak/AgentHound/releases/download/v0.6.1/agenthound_0.6.1_darwin_amd64.tar.gz"
      sha256 "6f9a58b7c0c61db180a2739ed981b977e5e3ced5078210e0fb75641c8e1ebb44"

      define_method(:install) do
        bin.install "agenthound"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/adithyan-ak/AgentHound/releases/download/v0.6.1/agenthound_0.6.1_darwin_arm64.tar.gz"
      sha256 "eae0aaac6c89e30a43f5e940814bf46f66e59b5c4519c46db77a8a72fe9d958a"

      define_method(:install) do
        bin.install "agenthound"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/adithyan-ak/AgentHound/releases/download/v0.6.1/agenthound_0.6.1_linux_amd64.tar.gz"
      sha256 "00754877e88070254c241f2b78c930e2b355d4fd8e5b6b3cd391454c87a46d10"
      define_method(:install) do
        bin.install "agenthound"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/adithyan-ak/AgentHound/releases/download/v0.6.1/agenthound_0.6.1_linux_arm64.tar.gz"
      sha256 "2085e21d9c19a4bb76cd626a78e413c1978100eb54c46ef456f3bfff50bcd576"
      define_method(:install) do
        bin.install "agenthound"
      end
    end
  end

  test do
    assert_match "agenthound", shell_output("#{bin}/agenthound --version")
  end
end
