# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AgenthoundServer < Formula
  desc "AgentHound — single-user server (Neo4j-backed graph + UI)"
  homepage "https://github.com/adithyan-ak/agenthound"
  version "0.8.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/adithyan-ak/AgentHound/releases/download/v0.8.0/agenthound-server_0.8.0_darwin_amd64.tar.gz"
      sha256 "887632806415a6cce79e9b4c456a31f1f88565f2e9ef119b70737bc6f4786ddf"

      define_method(:install) do
        bin.install "agenthound-server"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/adithyan-ak/AgentHound/releases/download/v0.8.0/agenthound-server_0.8.0_darwin_arm64.tar.gz"
      sha256 "da243e321acbd33dc03ba9480cfec8e3b1ae35a40cee05a87a103e6327eea4fd"

      define_method(:install) do
        bin.install "agenthound-server"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/adithyan-ak/AgentHound/releases/download/v0.8.0/agenthound-server_0.8.0_linux_amd64.tar.gz"
      sha256 "a00f788fee4cfa7aa93844dc82ca0d4dfcf0af50425d94f56dde7a0eb1ce41ad"
      define_method(:install) do
        bin.install "agenthound-server"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/adithyan-ak/AgentHound/releases/download/v0.8.0/agenthound-server_0.8.0_linux_arm64.tar.gz"
      sha256 "bf3934cf684481af61ae8f61c2fff5a10a426ff30ffb31e12ecfdf575ce32cde"
      define_method(:install) do
        bin.install "agenthound-server"
      end
    end
  end

  test do
    assert_match "agenthound-server", shell_output("#{bin}/agenthound-server --version")
  end
end
