# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AgenthoundServer < Formula
  desc "AgentHound — single-user server (Neo4j-backed graph + UI)"
  homepage "https://github.com/adithyan-ak/agenthound"
  version "0.6.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/adithyan-ak/AgentHound/releases/download/v0.6.1/agenthound-server_0.6.1_darwin_amd64.tar.gz"
      sha256 "8b75411c3e9e04ab5360eebdb1a9d40c274dcf9d2844e9bd0759ef25c60ff425"

      define_method(:install) do
        bin.install "agenthound-server"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/adithyan-ak/AgentHound/releases/download/v0.6.1/agenthound-server_0.6.1_darwin_arm64.tar.gz"
      sha256 "995a190d056e68be78e192acbe7ded6a30368c9d4a69cc9fd0e1c4584acf13ed"

      define_method(:install) do
        bin.install "agenthound-server"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/adithyan-ak/AgentHound/releases/download/v0.6.1/agenthound-server_0.6.1_linux_amd64.tar.gz"
      sha256 "4c00e18681ddde3c6574f917912a369c8ba66d9fe2a36a286fd3278fe29e70e4"
      define_method(:install) do
        bin.install "agenthound-server"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/adithyan-ak/AgentHound/releases/download/v0.6.1/agenthound-server_0.6.1_linux_arm64.tar.gz"
      sha256 "52d15b081ff1d291a4df825d7b82256957ffec8d281eb1a849d259c589c15a8a"
      define_method(:install) do
        bin.install "agenthound-server"
      end
    end
  end

  test do
    assert_match "agenthound-server", shell_output("#{bin}/agenthound-server --version")
  end
end
