# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Agenthound < Formula
  desc "Lean field collector for AI agent infrastructure"
  homepage "https://github.com/adithyan-ak/agenthound"
  version "1.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/adithyan-ak/AgentHound/releases/download/v1.0.1/agenthound_1.0.1_darwin_amd64.tar.gz"
      sha256 "f018cf1276aa73567217d22ba8fed48afc3718a44f9b7ce4a18d26e23e037dc1"

      define_method(:install) do
        bin.install "agenthound"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/adithyan-ak/AgentHound/releases/download/v1.0.1/agenthound_1.0.1_darwin_arm64.tar.gz"
      sha256 "b2b7406cd537eba979dd6f06d7913c6e8a3262efa2829b0e41cf94c980443076"

      define_method(:install) do
        bin.install "agenthound"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/adithyan-ak/AgentHound/releases/download/v1.0.1/agenthound_1.0.1_linux_amd64.tar.gz"
      sha256 "2030e0ffea393374dc134a2d6de8560c0c02a076283b58e92e3a635c690062de"
      define_method(:install) do
        bin.install "agenthound"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/adithyan-ak/AgentHound/releases/download/v1.0.1/agenthound_1.0.1_linux_arm64.tar.gz"
      sha256 "58685202da605bbafd8186736921485c10bbd1d2e03036ded53083335687f04e"
      define_method(:install) do
        bin.install "agenthound"
      end
    end
  end

  test do
    assert_match "agenthound", shell_output("#{bin}/agenthound --version")
  end
end
