# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AgenthoundServer < Formula
  desc "Single-user Neo4j-backed graph and UI for AgentHound"
  homepage "https://github.com/adithyan-ak/agenthound"
  version "0.9.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/adithyan-ak/AgentHound/releases/download/v0.9.0/agenthound-server_0.9.0_darwin_amd64.tar.gz"
      sha256 "7a6759ffc2e55204f9bab52d9158e2ebcc495acdcf2faaf2fb5d50ea2304853e"

      define_method(:install) do
        bin.install "agenthound-server"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/adithyan-ak/AgentHound/releases/download/v0.9.0/agenthound-server_0.9.0_darwin_arm64.tar.gz"
      sha256 "893222f66f98cbe10440c27329386ffe06444722531b24106fe154ae8ef88f2a"

      define_method(:install) do
        bin.install "agenthound-server"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/adithyan-ak/AgentHound/releases/download/v0.9.0/agenthound-server_0.9.0_linux_amd64.tar.gz"
      sha256 "e024130bba3621bda452b3d63be64ee8da73bb4dad06ac0e8cc497c7a6353b6f"
      define_method(:install) do
        bin.install "agenthound-server"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/adithyan-ak/AgentHound/releases/download/v0.9.0/agenthound-server_0.9.0_linux_arm64.tar.gz"
      sha256 "513c4087c6acbefc129dfb3bce9158b58abe7f39fe0688ea599fda8450581271"
      define_method(:install) do
        bin.install "agenthound-server"
      end
    end
  end

  test do
    assert_match "agenthound-server", shell_output("#{bin}/agenthound-server --version")
  end
end
