# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AgenthoundServer < Formula
  desc "AgentHound — single-user server (Neo4j-backed graph + UI)"
  homepage "https://github.com/adithyan-ak/agenthound"
  version "0.6.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/adithyan-ak/AgentHound/releases/download/v0.6.0/agenthound-server_0.6.0_darwin_amd64.tar.gz"
      sha256 "54723033f1a438b52ba6669a2ecba811e170987fccbf6a3d2a3d9d06e76d8386"

      define_method(:install) do
        bin.install "agenthound-server"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/adithyan-ak/AgentHound/releases/download/v0.6.0/agenthound-server_0.6.0_darwin_arm64.tar.gz"
      sha256 "945cd0fa7617b638caab942d3ab9c2a3193717db82e0329501299ec2ac47eb20"

      define_method(:install) do
        bin.install "agenthound-server"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/adithyan-ak/AgentHound/releases/download/v0.6.0/agenthound-server_0.6.0_linux_amd64.tar.gz"
      sha256 "2f4c6ca1a26e6d63d144f9025c5a1533028d6bf72b1304bd7f71bf3ddfb3f6a9"
      define_method(:install) do
        bin.install "agenthound-server"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/adithyan-ak/AgentHound/releases/download/v0.6.0/agenthound-server_0.6.0_linux_arm64.tar.gz"
      sha256 "6eaf90017b6c6f38e67446942503ba5cdc8dba4eb80c1a971602f2ad00e9741b"
      define_method(:install) do
        bin.install "agenthound-server"
      end
    end
  end

  test do
    assert_match "agenthound-server", shell_output("#{bin}/agenthound-server --version")
  end
end
