# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Agenthound < Formula
  desc "AgentHound — lean field collector for AI agent infrastructure"
  homepage "https://github.com/adithyan-ak/agenthound"
  version "0.6.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/adithyan-ak/AgentHound/releases/download/v0.6.0/agenthound_0.6.0_darwin_amd64.tar.gz"
      sha256 "3e84fa9b3dbc7b0f0e20d087f46d048d0a70751eb2c9ef8dab4800a96db44ba0"

      define_method(:install) do
        bin.install "agenthound"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/adithyan-ak/AgentHound/releases/download/v0.6.0/agenthound_0.6.0_darwin_arm64.tar.gz"
      sha256 "806b672b5520fd4a9634374eb29eeefaeb59538d4567a83340bb96dace35a1a5"

      define_method(:install) do
        bin.install "agenthound"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/adithyan-ak/AgentHound/releases/download/v0.6.0/agenthound_0.6.0_linux_amd64.tar.gz"
      sha256 "51cb216ea4dfb066a6108338094fc016f641b1a1d73c6c14929be45e88e6b339"
      define_method(:install) do
        bin.install "agenthound"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/adithyan-ak/AgentHound/releases/download/v0.6.0/agenthound_0.6.0_linux_arm64.tar.gz"
      sha256 "3b274dcea1e3a32004941fc1106e75fb8c10fe3d11dd3527eac2463529d723ab"
      define_method(:install) do
        bin.install "agenthound"
      end
    end
  end

  test do
    assert_match "agenthound", shell_output("#{bin}/agenthound --version")
  end
end
