# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Agenthound < Formula
  desc "Lean field collector for AI agent infrastructure"
  homepage "https://github.com/adithyan-ak/agenthound"
  version "1.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/adithyan-ak/AgentHound/releases/download/v1.0.0/agenthound_1.0.0_darwin_amd64.tar.gz"
      sha256 "210866166d407b2484cab0efc77b041d728a202d0b428a813c513e90ee1d4b39"

      define_method(:install) do
        bin.install "agenthound"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/adithyan-ak/AgentHound/releases/download/v1.0.0/agenthound_1.0.0_darwin_arm64.tar.gz"
      sha256 "d5df89479d85bc10191ee9fe75362cdda65887f915dff7748c2743157b42837c"

      define_method(:install) do
        bin.install "agenthound"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/adithyan-ak/AgentHound/releases/download/v1.0.0/agenthound_1.0.0_linux_amd64.tar.gz"
      sha256 "b1c6754d977d33132acc8b32728bd9b774e47310357c893e78a6985ffbe0c1fb"
      define_method(:install) do
        bin.install "agenthound"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/adithyan-ak/AgentHound/releases/download/v1.0.0/agenthound_1.0.0_linux_arm64.tar.gz"
      sha256 "30fa66fa983493cedad8be18b13b3a8f672fa3b0bbe3595d61e9bbb81c3521fa"
      define_method(:install) do
        bin.install "agenthound"
      end
    end
  end

  test do
    assert_match "agenthound", shell_output("#{bin}/agenthound --version")
  end
end
